"""Add reset_token and token_expiry to User model

Revision ID: 8807a1b68cb5
Revises: 1a061d726f12
Create Date: 2026-01-18 06:18:38.014807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8807a1b68cb5'
down_revision = '1a061d726f12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('token_expiry', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('token_expiry')
        batch_op.drop_column('reset_token')

    # ### end Alembic commands ###
