"""Add notes to shipments

Revision ID: ecea4ddfcba6
Revises: 8807a1b68cb5
Create Date: 2026-01-18 11:53:03.249465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecea4ddfcba6'
down_revision = '8807a1b68cb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
